bearer_token: "Bearer AAAAAAAAAAAAAAAAAAAAAPnA9gAAAAAAZHpqKYoDdMCaqTUBktzAdK38BGk%3DLNsI9r2BHSjZ7cl5wD6Sh6NhxwZd2j8lXDSd6GDoQVYBlzx5Ff"
link_network: "https://ads.x.com/accounts/18ce55pskui/media"
title: "OKOK"
number_of_threads: 1
number_post: 3
time_sleep_per_post: 10
